{add} fire base login
Android-3rd-Momo/MOMO pull request #14
Opened 2024-06-04 13:05 UTC by kmtso434

파이어 베이스 로그인 기능 추가되었습니다

2024-06-04 13:30 UTC, Winterwood0118 requested changes
전체적인 시작 로직이 현재로써는 main -(최초실행시만 getStarted? - main)으로 되어있는데 이부분도 생각이 조금 필요해보입니다.
코멘트 제외하고도 conflict해결하신다음에 다시 review 요청해주시면 감사하겠습니다.

2024-06-04 13:30 UTC, Winterwood0118 commented on app/build.gradle.kts
> +    implementation ("com.google.firebase:firebase-auth-ktx")
65, 66번 라인과 중복 dependency입니다! 지워주세용

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/main/MainActivity.kt
> +    }
기왕 DataStore 쓰기로한거 나중에 얘도 DataStore로 바꾸면 좋을 것 같습니다! 혹은 온보딩 노출을 Auth의 currentUser = null이면 하는 로직도 괜찮아보입니다

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/onboarding/login/LoginFragment.kt
> +        }
data layer에서부터 UserRepositoryImpl -> UserUseCase를 이용해 FireBase Auth 객체를 가지고 올 수 있습니다. 이미 dataLayer의 Module에서 싱글톤으로 호출되고 있어서 Null이 뜨는게 아닐까 싶습니다. 또한 MVVM패턴을 적용하기로 했으므로 ViewModel을 작성해서 데이터 가공은 ViewModel에서 처리하게 바꾸시면 되겠습니다.

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/onboarding/term/TermViewModel.kt
> +data class Term(val title: String, val look: String, var isAccepted: Boolean)
주석 넣으신대로 Model 패키지 만드셔서 거기에 dataClass 파일 만들어서 사용하시면 되겠습니다. 또한 data Class 내부에 var 사용은 지양하는 편이 좋기 때문에 해당 isAccepted 갱신은 Title과 look은 그대로 이어가고 isAccepted 값만 바꾼 새로운 객체를 만들어서 갱신하는게 좋을 것 같습니다!

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/onboarding/GetStartedActivity.kt
> +
Activity위에 login - onBoard - term이 존재하므로 해당 정보들을 받아 새로운 유저 정보를 만들 수 있게 공유 뷰모델 하나를 만드는 편이 좋아보입니다

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/onboarding/GetStartedViewPagerAdapter.kt
> +    inner class Pager2ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
중복 네이밍이나 메모리 문제 때문에 inner 키워드 지워주시는게 좋을 것 같습니다

2024-06-04 13:30 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/presentation/onboarding/GetStartedViewPagerAdapter.kt
> +        }
토스트를 itemView의 context에 의존하는건 위험해보입니다. 해당 클릭이벤트를 프래그먼트에서 주입해주는 방법을 고려해보시는게 좋겠습니다

2024-06-05 01:17 UTC, Winterwood0118 commented on app/build.gradle.kts
> +    implementation ("com.google.android.gms:play-services-auth:20.5.0")
66번 라인과 동일한 dependency입니다! 지워주세용

2024-06-05 01:36 UTC, Winterwood0118 approved these changes
확인했습니다

2024-06-05 01:36 UTC, Winterwood0118 commented on app/build.gradle.kts
> +    implementation ("com.google.android.gms:play-services-auth:20.1.0")
동일 dependency가 버전만 다르네용 이부분도 최신버전만 남기고 지워주시면 되겠습니다

2024-06-05 01:36 UTC, Winterwood0118 commented on app/build.gradle.kts
> +    implementation ("androidx.datastore:datastore-preferences:1.0.0")
86번라인과 중복입니다!

2024-06-05 01:37 UTC, Combro-Kim approved these changes
고생하셨습니다

2024-06-05 01:38 UTC, merged