Feature/mypage
Android-3rd-Momo/MOMO pull request #17
Opened 2024-06-07 05:29 UTC by Combro-Kim

- MyPage 이미지 업로드 기능 추가

2024-06-07 05:41 UTC, bonggyulim approved these changes
승인합니다 코멘트 답만 달아주세요

2024-06-07 05:41 UTC, bonggyulim commented on app/src/main/java/kr/nbc/momo/data/repository/UserRepositoryImpl.kt
> +            val backgroundImageUrl = if (user.userBackgroundThumbnailUrl.startsWith("content://")) {
content:// 는 추가하면 어떤점이 좋은가요??

2024-06-07 06:40 UTC, Combro-Kim commented on app/src/main/java/kr/nbc/momo/data/repository/UserRepositoryImpl.kt
> +            val backgroundImageUrl = if (user.userBackgroundThumbnailUrl.startsWith("content://")) {
수요일 에러에 관련된 코드입니다. 
아직 정확한 해결방법인지 모르지만 당장 해결한 방법은 getFile안에 content://로 시작하는 조건문을 추가해서 URI의 값을 구분했습니다.
트러블 슈팅에 작성 중이라 나중에 읽어보시기 좋게 작성해두겠습니다.

2024-06-07 09:12 UTC, Winterwood0118 requested changes
아까 낮에 말씀드린 부분 수정하시고 다시 요청주세용

2024-06-08 05:41 UTC, Winterwood0118 approved these changes
확인했습니다! 궁금한점 하나있고 유저정보에 가입된 그룹id넣어주세요!

2024-06-08 05:41 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/data/model/UserResponse.kt
유저가 들어간 그룹 리스트 넣어주세용

2024-06-08 05:41 UTC, Winterwood0118 commented on app/src/main/java/kr/nbc/momo/data/repository/UserRepositoryImpl.kt
> +    }
싱글톤이고 힐트 이용해서 제공하는거라 괜찮을것같긴한데 혹시 init으로 리스너 만들었을 때 메모리 누수나 중복호출, 로그아웃 시 리스너 잔여문제는 없을까요?

2024-06-08 05:47 UTC, bonggyulim approved these changes
고생하셨습니다

2024-06-08 05:48 UTC, kmtso434 approved these changes

2024-06-08 06:23 UTC, merged